services:
  app:
    build:
      context: ./
      dockerfile: docker-compose/laravel/main/Dockerfile
    image: local/jikokujo
    container_name: backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "php", "artisan", "migrate:status"]
      interval: 1m
      timeout: 30s
      retries: 10
      start_period: 3m
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - app-volume:/var/www
    depends_on:
      database:
        condition: service_healthy
    networks:
      - jikokujo

  database:
    image: mysql:9.6.0
    command: --restrict-fk-on-non-standard-key=OFF
    container_name: database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - jikokujo
  
  api:
    image: nginx:1.29.5
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    depends_on:
      reverb:
        condition: service_started
    volumes:
      - app-volume:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - jikokujo

  reverb:
    build:
      context: ./
      dockerfile: docker-compose/laravel/dependants/Dockerfile
    image: local/jikokujo-reverb
    container_name: reverb
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      app:
        condition: service_healthy
    command: php /var/www/artisan reverb:start --host=0.0.0.0 --port=${REVERB_PORT}
    networks:
      - jikokujo

  job-queue:
    build:
      context: ./
      dockerfile: docker-compose/laravel/dependants/Dockerfile
    image: local/jikokujo-job-queue
    container_name: job-queue
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      app:
        condition: service_healthy
    command: php /var/www/artisan queue:work database --sleep=3 --tries=3 --max-time=3600
    networks:
      - jikokujo

networks:
  jikokujo:
    driver: bridge

volumes:
  app-volume:
  database-volume: