[supervisord]
[program:jikokujo-reverb-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan reverb:start --port=8080
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
stdout_log=/var/www/storage/logs/reverb-worker.log
stopwaitsecs=3600