<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime\VehicleDescriptor;

use UnexpectedValueException;

/**
 * Protobuf type <code>transit_realtime.VehicleDescriptor.WheelchairAccessible</code>
 */
class WheelchairAccessible
{
    /**
     * Generated from protobuf enum <code>NO_VALUE = 0;</code>
     */
    const NO_VALUE = 0;
    /**
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * Generated from protobuf enum <code>WHEELCHAIR_ACCESSIBLE = 2;</code>
     */
    const WHEELCHAIR_ACCESSIBLE = 2;
    /**
     * Generated from protobuf enum <code>WHEELCHAIR_INACCESSIBLE = 3;</code>
     */
    const WHEELCHAIR_INACCESSIBLE = 3;

    private static $valueToName = [
        self::NO_VALUE => 'NO_VALUE',
        self::UNKNOWN => 'UNKNOWN',
        self::WHEELCHAIR_ACCESSIBLE => 'WHEELCHAIR_ACCESSIBLE',
        self::WHEELCHAIR_INACCESSIBLE => 'WHEELCHAIR_INACCESSIBLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

