<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.Alert</code>
 */
class Alert extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .transit_realtime.Alert.TimeRange active_period = 1;</code>
     */
    private $active_period;
    /**
     * Generated from protobuf field <code>.transit_realtime.Alert.Cause cause = 6;</code>
     */
    protected $cause = 0;
    /**
     * Generated from protobuf field <code>.transit_realtime.Alert.Effect effect = 7;</code>
     */
    protected $effect = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \TransitRealtime\Alert\TimeRange[] $active_period
     *     @type int $cause
     *     @type int $effect
     * }
     */
    public function __construct($data = NULL) {
        \TransitRealtime\GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .transit_realtime.Alert.TimeRange active_period = 1;</code>
     * @return RepeatedField<\TransitRealtime\Alert\TimeRange>
     */
    public function getActivePeriod()
    {
        return $this->active_period;
    }

    /**
     * Generated from protobuf field <code>repeated .transit_realtime.Alert.TimeRange active_period = 1;</code>
     * @param \TransitRealtime\Alert\TimeRange[] $var
     * @return $this
     */
    public function setActivePeriod($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \TransitRealtime\Alert\TimeRange::class);
        $this->active_period = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Alert.Cause cause = 6;</code>
     * @return int
     */
    public function getCause()
    {
        return $this->cause;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Alert.Cause cause = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCause($var)
    {
        GPBUtil::checkEnum($var, \TransitRealtime\Alert\Cause::class);
        $this->cause = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Alert.Effect effect = 7;</code>
     * @return int
     */
    public function getEffect()
    {
        return $this->effect;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Alert.Effect effect = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setEffect($var)
    {
        GPBUtil::checkEnum($var, \TransitRealtime\Alert\Effect::class);
        $this->effect = $var;

        return $this;
    }

}

