<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.FeedEntity</code>
 */
class FeedEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>bool is_deleted = 2;</code>
     */
    protected $is_deleted = false;
    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate trip_update = 3;</code>
     */
    protected $trip_update = null;
    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition vehicle = 4;</code>
     */
    protected $vehicle = null;
    /**
     * Generated from protobuf field <code>.transit_realtime.Alert alert = 5;</code>
     */
    protected $alert = null;
    /**
     * Generated from protobuf field <code>.transit_realtime.Shape shape = 6;</code>
     */
    protected $shape = null;
    /**
     * Generated from protobuf field <code>.transit_realtime.Stop stop = 7;</code>
     */
    protected $stop = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type bool $is_deleted
     *     @type \TransitRealtime\TripUpdate $trip_update
     *     @type \TransitRealtime\VehiclePosition $vehicle
     *     @type \TransitRealtime\Alert $alert
     *     @type \TransitRealtime\Shape $shape
     *     @type \TransitRealtime\Stop $stop
     * }
     */
    public function __construct($data = NULL) {
        \TransitRealtime\GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_deleted = 2;</code>
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->is_deleted;
    }

    /**
     * Generated from protobuf field <code>bool is_deleted = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->is_deleted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate trip_update = 3;</code>
     * @return \TransitRealtime\TripUpdate|null
     */
    public function getTripUpdate()
    {
        return $this->trip_update;
    }

    public function hasTripUpdate()
    {
        return isset($this->trip_update);
    }

    public function clearTripUpdate()
    {
        unset($this->trip_update);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate trip_update = 3;</code>
     * @param \TransitRealtime\TripUpdate $var
     * @return $this
     */
    public function setTripUpdate($var)
    {
        GPBUtil::checkMessage($var, \TransitRealtime\TripUpdate::class);
        $this->trip_update = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition vehicle = 4;</code>
     * @return \TransitRealtime\VehiclePosition|null
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    public function hasVehicle()
    {
        return isset($this->vehicle);
    }

    public function clearVehicle()
    {
        unset($this->vehicle);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition vehicle = 4;</code>
     * @param \TransitRealtime\VehiclePosition $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkMessage($var, \TransitRealtime\VehiclePosition::class);
        $this->vehicle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Alert alert = 5;</code>
     * @return \TransitRealtime\Alert|null
     */
    public function getAlert()
    {
        return $this->alert;
    }

    public function hasAlert()
    {
        return isset($this->alert);
    }

    public function clearAlert()
    {
        unset($this->alert);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Alert alert = 5;</code>
     * @param \TransitRealtime\Alert $var
     * @return $this
     */
    public function setAlert($var)
    {
        GPBUtil::checkMessage($var, \TransitRealtime\Alert::class);
        $this->alert = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Shape shape = 6;</code>
     * @return \TransitRealtime\Shape|null
     */
    public function getShape()
    {
        return $this->shape;
    }

    public function hasShape()
    {
        return isset($this->shape);
    }

    public function clearShape()
    {
        unset($this->shape);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Shape shape = 6;</code>
     * @param \TransitRealtime\Shape $var
     * @return $this
     */
    public function setShape($var)
    {
        GPBUtil::checkMessage($var, \TransitRealtime\Shape::class);
        $this->shape = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Stop stop = 7;</code>
     * @return \TransitRealtime\Stop|null
     */
    public function getStop()
    {
        return $this->stop;
    }

    public function hasStop()
    {
        return isset($this->stop);
    }

    public function clearStop()
    {
        unset($this->stop);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Stop stop = 7;</code>
     * @param \TransitRealtime\Stop $var
     * @return $this
     */
    public function setStop($var)
    {
        GPBUtil::checkMessage($var, \TransitRealtime\Stop::class);
        $this->stop = $var;

        return $this;
    }

}

