<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.Position</code>
 */
class Position extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float latitude = 1;</code>
     */
    protected $latitude = 0.0;
    /**
     * Generated from protobuf field <code>float longitude = 2;</code>
     */
    protected $longitude = 0.0;
    /**
     * Generated from protobuf field <code>float bearing = 3;</code>
     */
    protected $bearing = 0.0;
    /**
     * Generated from protobuf field <code>double odometer = 4;</code>
     */
    protected $odometer = 0.0;
    /**
     * Generated from protobuf field <code>float speed = 5;</code>
     */
    protected $speed = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $latitude
     *     @type float $longitude
     *     @type float $bearing
     *     @type float $odometer
     *     @type float $speed
     * }
     */
    public function __construct($data = NULL) {
        \TransitRealtime\GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float latitude = 1;</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Generated from protobuf field <code>float latitude = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float longitude = 2;</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Generated from protobuf field <code>float longitude = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->longitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float bearing = 3;</code>
     * @return float
     */
    public function getBearing()
    {
        return $this->bearing;
    }

    /**
     * Generated from protobuf field <code>float bearing = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setBearing($var)
    {
        GPBUtil::checkFloat($var);
        $this->bearing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double odometer = 4;</code>
     * @return float
     */
    public function getOdometer()
    {
        return $this->odometer;
    }

    /**
     * Generated from protobuf field <code>double odometer = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setOdometer($var)
    {
        GPBUtil::checkDouble($var);
        $this->odometer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float speed = 5;</code>
     * @return float
     */
    public function getSpeed()
    {
        return $this->speed;
    }

    /**
     * Generated from protobuf field <code>float speed = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setSpeed($var)
    {
        GPBUtil::checkFloat($var);
        $this->speed = $var;

        return $this;
    }

}

