<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.Shape</code>
 */
class Shape extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string shape_id = 1;</code>
     */
    protected $shape_id = '';
    /**
     * Generated from protobuf field <code>string encoded_polyline = 2;</code>
     */
    protected $encoded_polyline = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $shape_id
     *     @type string $encoded_polyline
     * }
     */
    public function __construct($data = NULL) {
        \TransitRealtime\GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string shape_id = 1;</code>
     * @return string
     */
    public function getShapeId()
    {
        return $this->shape_id;
    }

    /**
     * Generated from protobuf field <code>string shape_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShapeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shape_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string encoded_polyline = 2;</code>
     * @return string
     */
    public function getEncodedPolyline()
    {
        return $this->encoded_polyline;
    }

    /**
     * Generated from protobuf field <code>string encoded_polyline = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEncodedPolyline($var)
    {
        GPBUtil::checkString($var, True);
        $this->encoded_polyline = $var;

        return $this;
    }

}

