<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.Stop</code>
 */
class Stop extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string stop_id = 1;</code>
     */
    protected $stop_id = '';
    /**
     * Generated from protobuf field <code>float stop_lat = 6;</code>
     */
    protected $stop_lat = 0.0;
    /**
     * Generated from protobuf field <code>float stop_lon = 7;</code>
     */
    protected $stop_lon = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stop_id
     *     @type float $stop_lat
     *     @type float $stop_lon
     * }
     */
    public function __construct($data = NULL) {
        \TransitRealtime\GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string stop_id = 1;</code>
     * @return string
     */
    public function getStopId()
    {
        return $this->stop_id;
    }

    /**
     * Generated from protobuf field <code>string stop_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float stop_lat = 6;</code>
     * @return float
     */
    public function getStopLat()
    {
        return $this->stop_lat;
    }

    /**
     * Generated from protobuf field <code>float stop_lat = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setStopLat($var)
    {
        GPBUtil::checkFloat($var);
        $this->stop_lat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float stop_lon = 7;</code>
     * @return float
     */
    public function getStopLon()
    {
        return $this->stop_lon;
    }

    /**
     * Generated from protobuf field <code>float stop_lon = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setStopLon($var)
    {
        GPBUtil::checkFloat($var);
        $this->stop_lon = $var;

        return $this;
    }

}

