<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.TripUpdate</code>
 */
class TripUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor trip = 1;</code>
     */
    protected $trip = null;
    /**
     * Generated from protobuf field <code>.transit_realtime.VehicleDescriptor vehicle = 3;</code>
     */
    protected $vehicle = null;
    /**
     * Generated from protobuf field <code>repeated .transit_realtime.TripUpdate.StopTimeUpdate stop_time_update = 2;</code>
     */
    private $stop_time_update;
    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \TransitRealtime\TripDescriptor $trip
     *     @type \TransitRealtime\VehicleDescriptor $vehicle
     *     @type \TransitRealtime\TripUpdate\StopTimeUpdate[] $stop_time_update
     *     @type int|string $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \TransitRealtime\GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor trip = 1;</code>
     * @return \TransitRealtime\TripDescriptor|null
     */
    public function getTrip()
    {
        return $this->trip;
    }

    public function hasTrip()
    {
        return isset($this->trip);
    }

    public function clearTrip()
    {
        unset($this->trip);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor trip = 1;</code>
     * @param \TransitRealtime\TripDescriptor $var
     * @return $this
     */
    public function setTrip($var)
    {
        GPBUtil::checkMessage($var, \TransitRealtime\TripDescriptor::class);
        $this->trip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehicleDescriptor vehicle = 3;</code>
     * @return \TransitRealtime\VehicleDescriptor|null
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    public function hasVehicle()
    {
        return isset($this->vehicle);
    }

    public function clearVehicle()
    {
        unset($this->vehicle);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehicleDescriptor vehicle = 3;</code>
     * @param \TransitRealtime\VehicleDescriptor $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkMessage($var, \TransitRealtime\VehicleDescriptor::class);
        $this->vehicle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .transit_realtime.TripUpdate.StopTimeUpdate stop_time_update = 2;</code>
     * @return RepeatedField<\TransitRealtime\TripUpdate\StopTimeUpdate>
     */
    public function getStopTimeUpdate()
    {
        return $this->stop_time_update;
    }

    /**
     * Generated from protobuf field <code>repeated .transit_realtime.TripUpdate.StopTimeUpdate stop_time_update = 2;</code>
     * @param \TransitRealtime\TripUpdate\StopTimeUpdate[] $var
     * @return $this
     */
    public function setStopTimeUpdate($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \TransitRealtime\TripUpdate\StopTimeUpdate::class);
        $this->stop_time_update = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

}

