<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.VehicleDescriptor</code>
 */
class VehicleDescriptor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string label = 2;</code>
     */
    protected $label = '';
    /**
     * Generated from protobuf field <code>string license_plate = 3;</code>
     */
    protected $license_plate = '';
    /**
     * Generated from protobuf field <code>.transit_realtime.VehicleDescriptor.WheelchairAccessible wheelchair_accessible = 4;</code>
     */
    protected $wheelchair_accessible = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $label
     *     @type string $license_plate
     *     @type int $wheelchair_accessible
     * }
     */
    public function __construct($data = NULL) {
        \TransitRealtime\GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string license_plate = 3;</code>
     * @return string
     */
    public function getLicensePlate()
    {
        return $this->license_plate;
    }

    /**
     * Generated from protobuf field <code>string license_plate = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLicensePlate($var)
    {
        GPBUtil::checkString($var, True);
        $this->license_plate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehicleDescriptor.WheelchairAccessible wheelchair_accessible = 4;</code>
     * @return int
     */
    public function getWheelchairAccessible()
    {
        return $this->wheelchair_accessible;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehicleDescriptor.WheelchairAccessible wheelchair_accessible = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setWheelchairAccessible($var)
    {
        GPBUtil::checkEnum($var, \TransitRealtime\VehicleDescriptor\WheelchairAccessible::class);
        $this->wheelchair_accessible = $var;

        return $this;
    }

}

