<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.VehiclePosition</code>
 */
class VehiclePosition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor trip = 1;</code>
     */
    protected $trip = null;
    /**
     * Generated from protobuf field <code>.transit_realtime.VehicleDescriptor vehicle = 8;</code>
     */
    protected $vehicle = null;
    /**
     * Generated from protobuf field <code>.transit_realtime.Position position = 2;</code>
     */
    protected $position = null;
    /**
     * Generated from protobuf field <code>uint32 current_stop_sequence = 3;</code>
     */
    protected $current_stop_sequence = 0;
    /**
     * Generated from protobuf field <code>string stop_id = 7;</code>
     */
    protected $stop_id = '';
    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition.VehicleStopStatus current_status = 4;</code>
     */
    protected $current_status = 0;
    /**
     * Generated from protobuf field <code>uint64 timestamp = 5;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
     */
    protected $congestion_level = 0;
    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition.OccupancyStatus occupancy_status = 9;</code>
     */
    protected $occupancy_status = 0;
    /**
     * Generated from protobuf field <code>uint32 occupancy_percentage = 10;</code>
     */
    protected $occupancy_percentage = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \TransitRealtime\TripDescriptor $trip
     *     @type \TransitRealtime\VehicleDescriptor $vehicle
     *     @type \TransitRealtime\Position $position
     *     @type int $current_stop_sequence
     *     @type string $stop_id
     *     @type int $current_status
     *     @type int|string $timestamp
     *     @type int $congestion_level
     *     @type int $occupancy_status
     *     @type int $occupancy_percentage
     * }
     */
    public function __construct($data = NULL) {
        \TransitRealtime\GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor trip = 1;</code>
     * @return \TransitRealtime\TripDescriptor|null
     */
    public function getTrip()
    {
        return $this->trip;
    }

    public function hasTrip()
    {
        return isset($this->trip);
    }

    public function clearTrip()
    {
        unset($this->trip);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor trip = 1;</code>
     * @param \TransitRealtime\TripDescriptor $var
     * @return $this
     */
    public function setTrip($var)
    {
        GPBUtil::checkMessage($var, \TransitRealtime\TripDescriptor::class);
        $this->trip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehicleDescriptor vehicle = 8;</code>
     * @return \TransitRealtime\VehicleDescriptor|null
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    public function hasVehicle()
    {
        return isset($this->vehicle);
    }

    public function clearVehicle()
    {
        unset($this->vehicle);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehicleDescriptor vehicle = 8;</code>
     * @param \TransitRealtime\VehicleDescriptor $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkMessage($var, \TransitRealtime\VehicleDescriptor::class);
        $this->vehicle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Position position = 2;</code>
     * @return \TransitRealtime\Position|null
     */
    public function getPosition()
    {
        return $this->position;
    }

    public function hasPosition()
    {
        return isset($this->position);
    }

    public function clearPosition()
    {
        unset($this->position);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.Position position = 2;</code>
     * @param \TransitRealtime\Position $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkMessage($var, \TransitRealtime\Position::class);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 current_stop_sequence = 3;</code>
     * @return int
     */
    public function getCurrentStopSequence()
    {
        return $this->current_stop_sequence;
    }

    /**
     * Generated from protobuf field <code>uint32 current_stop_sequence = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentStopSequence($var)
    {
        GPBUtil::checkUint32($var);
        $this->current_stop_sequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stop_id = 7;</code>
     * @return string
     */
    public function getStopId()
    {
        return $this->stop_id;
    }

    /**
     * Generated from protobuf field <code>string stop_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition.VehicleStopStatus current_status = 4;</code>
     * @return int
     */
    public function getCurrentStatus()
    {
        return $this->current_status;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition.VehicleStopStatus current_status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentStatus($var)
    {
        GPBUtil::checkEnum($var, \TransitRealtime\VehiclePosition\VehicleStopStatus::class);
        $this->current_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 5;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
     * @return int
     */
    public function getCongestionLevel()
    {
        return $this->congestion_level;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCongestionLevel($var)
    {
        GPBUtil::checkEnum($var, \TransitRealtime\VehiclePosition\CongestionLevel::class);
        $this->congestion_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition.OccupancyStatus occupancy_status = 9;</code>
     * @return int
     */
    public function getOccupancyStatus()
    {
        return $this->occupancy_status;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.VehiclePosition.OccupancyStatus occupancy_status = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setOccupancyStatus($var)
    {
        GPBUtil::checkEnum($var, \TransitRealtime\VehiclePosition\OccupancyStatus::class);
        $this->occupancy_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 occupancy_percentage = 10;</code>
     * @return int
     */
    public function getOccupancyPercentage()
    {
        return $this->occupancy_percentage;
    }

    /**
     * Generated from protobuf field <code>uint32 occupancy_percentage = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setOccupancyPercentage($var)
    {
        GPBUtil::checkUint32($var);
        $this->occupancy_percentage = $var;

        return $this;
    }

}

