<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime\VehiclePosition;

use UnexpectedValueException;

/**
 * Protobuf type <code>transit_realtime.VehiclePosition.OccupancyStatus</code>
 */
class OccupancyStatus
{
    /**
     * Generated from protobuf enum <code>EMPTY = 0;</code>
     */
    const PBEMPTY = 0;
    /**
     * Generated from protobuf enum <code>MANY_SEATS_AVAILABLE = 1;</code>
     */
    const MANY_SEATS_AVAILABLE = 1;
    /**
     * Generated from protobuf enum <code>FEW_SEATS_AVAILABLE = 2;</code>
     */
    const FEW_SEATS_AVAILABLE = 2;
    /**
     * Generated from protobuf enum <code>STANDING_ROOM_ONLY = 3;</code>
     */
    const STANDING_ROOM_ONLY = 3;
    /**
     * Generated from protobuf enum <code>CRUSHED_STANDING_ROOM_ONLY = 4;</code>
     */
    const CRUSHED_STANDING_ROOM_ONLY = 4;
    /**
     * Generated from protobuf enum <code>FULL = 5;</code>
     */
    const FULL = 5;
    /**
     * Generated from protobuf enum <code>NOT_ACCEPTING_PASSENGERS = 6;</code>
     */
    const NOT_ACCEPTING_PASSENGERS = 6;
    /**
     * Generated from protobuf enum <code>NO_DATA_AVAILABLE = 7;</code>
     */
    const NO_DATA_AVAILABLE = 7;
    /**
     * Generated from protobuf enum <code>NOT_BOARDABLE = 8;</code>
     */
    const NOT_BOARDABLE = 8;

    private static $valueToName = [
        self::PBEMPTY => 'EMPTY',
        self::MANY_SEATS_AVAILABLE => 'MANY_SEATS_AVAILABLE',
        self::FEW_SEATS_AVAILABLE => 'FEW_SEATS_AVAILABLE',
        self::STANDING_ROOM_ONLY => 'STANDING_ROOM_ONLY',
        self::CRUSHED_STANDING_ROOM_ONLY => 'CRUSHED_STANDING_ROOM_ONLY',
        self::FULL => 'FULL',
        self::NOT_ACCEPTING_PASSENGERS => 'NOT_ACCEPTING_PASSENGERS',
        self::NO_DATA_AVAILABLE => 'NO_DATA_AVAILABLE',
        self::NOT_BOARDABLE => 'NOT_BOARDABLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            $pbconst =  __CLASS__. '::PB' . strtoupper($name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                        'Enum %s has no value defined for name %s', __CLASS__, $name));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

