<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime\VehiclePosition;

use UnexpectedValueException;

/**
 * Protobuf type <code>transit_realtime.VehiclePosition.VehicleStopStatus</code>
 */
class VehicleStopStatus
{
    /**
     * Generated from protobuf enum <code>INCOMING_AT = 0;</code>
     */
    const INCOMING_AT = 0;
    /**
     * Generated from protobuf enum <code>STOPPED_AT = 1;</code>
     */
    const STOPPED_AT = 1;
    /**
     * Generated from protobuf enum <code>IN_TRANSIT_TO = 2;</code>
     */
    const IN_TRANSIT_TO = 2;

    private static $valueToName = [
        self::INCOMING_AT => 'INCOMING_AT',
        self::STOPPED_AT => 'STOPPED_AT',
        self::IN_TRANSIT_TO => 'IN_TRANSIT_TO',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

