<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime\Alert;

use UnexpectedValueException;

/**
 * Protobuf type <code>transit_realtime.Alert.Cause</code>
 */
class Cause
{
    /**
     * Generated from protobuf enum <code>CAUSE_UNSPECIFIED = 0;</code>
     */
    const CAUSE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>UNKNOWN_CAUSE = 1;</code>
     */
    const UNKNOWN_CAUSE = 1;
    /**
     * Generated from protobuf enum <code>OTHER_CAUSE = 2;</code>
     */
    const OTHER_CAUSE = 2;
    /**
     * Generated from protobuf enum <code>TECHNICAL_PROBLEM = 3;</code>
     */
    const TECHNICAL_PROBLEM = 3;
    /**
     * Generated from protobuf enum <code>STRIKE = 4;</code>
     */
    const STRIKE = 4;
    /**
     * Generated from protobuf enum <code>DEMONSTRATION = 5;</code>
     */
    const DEMONSTRATION = 5;
    /**
     * Generated from protobuf enum <code>ACCIDENT = 6;</code>
     */
    const ACCIDENT = 6;
    /**
     * Generated from protobuf enum <code>HOLIDAY = 7;</code>
     */
    const HOLIDAY = 7;
    /**
     * Generated from protobuf enum <code>WEATHER = 8;</code>
     */
    const WEATHER = 8;
    /**
     * Generated from protobuf enum <code>MAINTENANCE = 9;</code>
     */
    const MAINTENANCE = 9;
    /**
     * Generated from protobuf enum <code>CONSTRUCTION = 10;</code>
     */
    const CONSTRUCTION = 10;
    /**
     * Generated from protobuf enum <code>POLICE_ACTIVITY = 11;</code>
     */
    const POLICE_ACTIVITY = 11;
    /**
     * Generated from protobuf enum <code>MEDICAL_EMERGENCY = 12;</code>
     */
    const MEDICAL_EMERGENCY = 12;

    private static $valueToName = [
        self::CAUSE_UNSPECIFIED => 'CAUSE_UNSPECIFIED',
        self::UNKNOWN_CAUSE => 'UNKNOWN_CAUSE',
        self::OTHER_CAUSE => 'OTHER_CAUSE',
        self::TECHNICAL_PROBLEM => 'TECHNICAL_PROBLEM',
        self::STRIKE => 'STRIKE',
        self::DEMONSTRATION => 'DEMONSTRATION',
        self::ACCIDENT => 'ACCIDENT',
        self::HOLIDAY => 'HOLIDAY',
        self::WEATHER => 'WEATHER',
        self::MAINTENANCE => 'MAINTENANCE',
        self::CONSTRUCTION => 'CONSTRUCTION',
        self::POLICE_ACTIVITY => 'POLICE_ACTIVITY',
        self::MEDICAL_EMERGENCY => 'MEDICAL_EMERGENCY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

