<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/gtfs-realtime.proto

namespace TransitRealtime\TripUpdate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.TripUpdate.StopTimeEvent</code>
 */
class StopTimeEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 delay = 1;</code>
     */
    protected $delay = 0;
    /**
     * Generated from protobuf field <code>int64 time = 2;</code>
     */
    protected $time = 0;
    /**
     * Generated from protobuf field <code>int32 uncertainty = 3;</code>
     */
    protected $uncertainty = 0;
    /**
     * Generated from protobuf field <code>int64 scheduled_time = 4;</code>
     */
    protected $scheduled_time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $delay
     *     @type int|string $time
     *     @type int $uncertainty
     *     @type int|string $scheduled_time
     * }
     */
    public function __construct($data = NULL) {
        \TransitRealtime\GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 delay = 1;</code>
     * @return int
     */
    public function getDelay()
    {
        return $this->delay;
    }

    /**
     * Generated from protobuf field <code>int32 delay = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDelay($var)
    {
        GPBUtil::checkInt32($var);
        $this->delay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 time = 2;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>int64 time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 uncertainty = 3;</code>
     * @return int
     */
    public function getUncertainty()
    {
        return $this->uncertainty;
    }

    /**
     * Generated from protobuf field <code>int32 uncertainty = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUncertainty($var)
    {
        GPBUtil::checkInt32($var);
        $this->uncertainty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 scheduled_time = 4;</code>
     * @return int|string
     */
    public function getScheduledTime()
    {
        return $this->scheduled_time;
    }

    /**
     * Generated from protobuf field <code>int64 scheduled_time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScheduledTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->scheduled_time = $var;

        return $this;
    }

}

